tables:
    - name: t_sync_01
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_01
      target_table: t_sync_01
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_02
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_02
      target_table: t_sync_02
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_03
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_03
      target_table: t_sync_03
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_04
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_04
      target_table: t_sync_04
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_05
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_05
      target_table: t_sync_05
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_06
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_06
      target_table: t_sync_06
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_07
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_07
      target_table: t_sync_07
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_08
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_08
      target_table: t_sync_08
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_09
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_09
      target_table: t_sync_09
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
    - name: t_sync_10
      brokers:
        - kafka:9092
      rows_per_partition: 1000000
      batch_size: 10000
      group_name: ch-sync-t_sync_10
      target_table: t_sync_10
      target_database: demo
      current_database: demo
      export_order_by: ""
      export_key_column: ""
      cursor_column: created_at
      cursor_start: "1970-01-01 00:00:00"
      cursor_end: ""
